// Re-export all table types from Drizzle schema
export type {
  Driver,
  InsertDriver,
  Vehicle,
  InsertVehicle,
  Location,
  InsertLocation,
  WeeklySchedule,
  InsertWeeklySchedule,
  DriverAvailability,
  InsertDriverAvailability,
  MissionRequest,
  InsertMissionRequest,
  Tour,
  InsertTour,
  TourStop,
  InsertTourStop,
  TravelTimeCache,
  InsertTravelTimeCache,
} from '@/lib/db/schema'
